tracer.property: "I AM THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform: "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.h2.Driver"
spring.datasource.url: "jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1"


jdbc:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: create

