tracer.property: "I AM THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform: "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://postgres:5432/catalog"
spring.datasource.username: "root"
spring.datasource.password: "admin"

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cloud:
    stream:
      kafka:
        binder:
          zkNodes: kafka1
          brokers: kafka1
        bindings:
          imageChangeTopic-out:
            destination: imageChangeTopic-out
            content-type: application/json

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
