eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      authentication-database: admin
      username: root
      password: admin
      database: image-service

  cloud:
    stream:
      kafka:
        binder:
          zkNodes: kafka1
          brokers: kafka1
        bindings:
          output:
            destination: imageChangeTopic
            content-type: application/json