version: '3.3'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: root
      POSTGRES_DB: catalog
    volumes:
      - ./init:/docker-entrypoint-initdb.d/

  catalog-service:
    build: ./catalog-service
    ports:
      - "18081:8081"
    depends_on:
      - config-service
      - postgres
    restart: on-failure

  config-service:
    build: ./config-service
    ports:
      - "18888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  discovery-service:
    build: ./discovery-service
    ports:
      - "18761:8761"

  image-service:
    build: ./image-service
    ports:
      - "18082:8082"
    depends_on:
      - config-service
    restart: on-failure