version: '3.3'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: root
      POSTGRES_DB: catalog
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
  catalog-service:
    build: ./catalog-service
    ports:
      - "8081:8081"
    depends_on:
      - config-service
    restart: on-failure
  config-service:
    build: ./config-service
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5