version: '3.3'
services:
  catalog-service:
    build: ./catalog-service
    ports:
      - "8081:8081"
    depends_on:
      - config-service
    restart: on-failure
  config-service:
    build: ./config-service
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5